// app/data.jsx — full data model for the 12 agents + i18n strings.
// Reuses STATUS, L from agent-cards.jsx (loaded earlier).

// ---------------- App-wide UI strings ----------------
const T = {
  brand:       { en: "Agent Orchestration", th: "ศูนย์ควบคุมเอเจนต์" },
  brandSub:    { en: "Content Operations", th: "ฝ่ายปฏิบัติการคอนเทนต์" },
  nav_dash:    { en: "Dashboard", th: "แดชบอร์ด" },
  nav_team:    { en: "The Team", th: "ทีมงาน" },
  nav_pipeline:{ en: "Pipeline", th: "ไปป์ไลน์" },
  live:        { en: "Live", th: "เรียลไทม์" },
  // dashboard
  d_title:     { en: "Operations Dashboard", th: "แดชบอร์ดปฏิบัติการ" },
  d_sub:       { en: "What every agent is doing, right now", th: "ดูว่าทุกเอเจนต์กำลังทำอะไรอยู่ตอนนี้" },
  k_active:    { en: "Active", th: "กำลังทำงาน" },
  k_thinking:  { en: "Thinking", th: "กำลังคิด" },
  k_idle:      { en: "Idle", th: "ว่าง" },
  k_error:     { en: "Needs help", th: "ต้องช่วย" },
  k_throughput:{ en: "Listings / hr", th: "ประกาศ / ชม." },
  k_queue:     { en: "In queue", th: "ในคิว" },
  sec_team:    { en: "Team status", th: "สถานะทีม" },
  sec_feed:    { en: "Activity feed", th: "ฟีดกิจกรรม" },
  sec_queue:   { en: "Task queue", th: "คิวงาน" },
  sec_pipe:    { en: "Listing pipeline", th: "ไปป์ไลน์ประกาศ" },
  viewAll:     { en: "View all", th: "ดูทั้งหมด" },
  waiting:     { en: "waiting", th: "รออยู่" },
  running:     { en: "running", th: "กำลังทำ" },
  // roster
  r_title:     { en: "The Team", th: "ทีมงาน" },
  r_sub:       { en: "12 specialists, one content factory", th: "12 ผู้เชี่ยวชาญ หนึ่งโรงงานคอนเทนต์" },
  filterAll:   { en: "All", th: "ทั้งหมด" },
  // detail tabs
  t_overview:  { en: "Overview", th: "ภาพรวม" },
  t_skills:    { en: "Skills", th: "ทักษะ" },
  t_memory:    { en: "Memory", th: "ความจำ" },
  t_process:   { en: "Workflow", th: "ขั้นตอนงาน" },
  t_history:   { en: "History", th: "ประวัติงาน" },
  t_tools:     { en: "Tools", th: "เครื่องมือ" },
  now:         { en: "Working on", th: "กำลังทำ" },
  reportsTo:   { en: "Reports to", th: "ขึ้นกับ" },
  manages:     { en: "Manages", th: "ดูแล" },
  persona:     { en: "Personality", th: "บุคลิก" },
  tasksDone:   { en: "Tasks done", th: "งานเสร็จ" },
  accuracy:    { en: "Accuracy", th: "ความแม่นยำ" },
  avgTime:     { en: "Avg time", th: "เวลาเฉลี่ย" },
  uptime:      { en: "Uptime", th: "ออนไลน์" },
  back:        { en: "Back", th: "กลับ" },
  memHint:     { en: "What this agent keeps in context across jobs", th: "สิ่งที่เอเจนต์จำไว้ใช้ข้ามงาน" },
  procHint:    { en: "How a job moves through this agent", th: "งานเดินผ่านเอเจนต์นี้อย่างไร" },
  recent:      { en: "Recent activity", th: "กิจกรรมล่าสุด" },
  empty:       { en: "Nothing in the queue", th: "ไม่มีงานในคิว" },
  step:        { en: "Step", th: "ขั้น" },
  lastUsed:    { en: "last used", th: "ใช้ล่าสุด" },
  proficiency: { en: "Proficiency", th: "ความเชี่ยวชาญ" },
  // memory types
  m_fact:      { en: "Fact", th: "ข้อเท็จจริง" },
  m_pattern:   { en: "Pattern", th: "รูปแบบ" },
  m_pref:      { en: "Preference", th: "ความชอบ" },
  m_context:   { en: "Context", th: "บริบท" },
};

const MEMTYPE = {
  fact:    { color: "#0E9E78", soft: "#E4F4EE", label: T.m_fact },
  pattern: { color: "#4F63D2", soft: "#E9ECFA", label: T.m_pattern },
  pref:    { color: "#C99528", soft: "#FAF1DC", label: T.m_pref },
  context: { color: "#D45B3C", soft: "#FBE8E2", label: T.m_context },
};

// ---------------- The 12 agents ----------------
const TEAM = [
  {
    id: "cco", code: "CCO-01", lead: true,
    name: { en: "Ada Chen", th: "เอด้า เฉิน" },
    role: { en: "Chief Content Officer", th: "หัวหน้าฝ่ายคอนเทนต์" },
    dept: "leadership", status: "thinking",
    blurb: { en: "The conductor. Decides who works on what, and when a listing ships.", th: "ผู้ควบคุมวง ตัดสินว่าใครทำอะไร และประกาศจะเผยแพร่เมื่อไร" },
    traits: [{ en: "Strategic", th: "มองภาพรวม" }, { en: "Decisive", th: "เด็ดขาด" }, { en: "High standards", th: "มาตรฐานสูง" }],
    manages: 11,
    skills: [
      { name: { en: "Orchestration", th: "ควบคุมทีม" }, level: 98 },
      { name: { en: "Quality strategy", th: "วางกลยุทธ์คุณภาพ" }, level: 93 },
      { name: { en: "Delegation", th: "มอบหมายงาน" }, level: 95 },
      { name: { en: "Final review", th: "ตรวจขั้นสุดท้าย" }, level: 91 },
    ],
    process: [
      { en: "Intake new listings", th: "รับประกาศใหม่เข้า" },
      { en: "Plan the pipeline", th: "วางลำดับงานในไปป์ไลน์" },
      { en: "Delegate to specialists", th: "มอบงานให้ผู้เชี่ยวชาญ" },
      { en: "Review & publish", th: "ตรวจขั้นสุดท้าย & เผยแพร่" },
    ],
    tools: ["Agent registry", "Task router", "Quality dashboard", "Publish API"],
    memory: [
      { type: "pref", text: { en: "Brand voice: warm, factual, never hype.", th: "โทนแบรนด์: อบอุ่น อิงข้อเท็จจริง ไม่โอเวอร์" } },
      { type: "fact", text: { en: "Publish target: 120 listings / day.", th: "เป้าเผยแพร่: 120 ประกาศ / วัน" } },
      { type: "pattern", text: { en: "Sukhumvit condos convert best with transit-first copy.", th: "คอนโดสุขุมวิทแปลงผลดีสุดเมื่อเน้นการเดินทางก่อน" } },
      { type: "context", text: { en: "Q3 push: Phuket pool villas are priority.", th: "โฟกัส Q3: พูลวิลล่าภูเก็ตเป็นงานสำคัญ" } },
    ],
    tasks: [
      { en: "Routing 38 listings to specialists", th: "จัดสรร 38 ประกาศให้ผู้เชี่ยวชาญ" },
      { en: "Reviewing Noble Ploenchit batch", th: "ตรวจชุดโนเบิล เพลินจิต" },
      { en: "Re-prioritising Phuket queue", th: "จัดลำดับคิวภูเก็ตใหม่" },
    ],
    stats: { done: "12.4k", acc: "99.1%", avg: "—", uptime: "99.9%" },
  },
  {
    id: "auditor", code: "LA-02",
    name: { en: "Somsak Pansuk", th: "สมศักดิ์ พันสุข" },
    role: { en: "Listing Auditor", th: "ผู้ตรวจสอบประกาศ" },
    dept: "quality", status: "active",
    blurb: { en: "Methodical, allergic to duplicates and stale prices.", th: "ละเอียด เกลียดประกาศซ้ำและราคาตกค้าง" },
    traits: [{ en: "Meticulous", th: "ละเอียด" }, { en: "Skeptical", th: "ช่างสงสัย" }, { en: "Fast", th: "รวดเร็ว" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Duplicate detection", th: "จับประกาศซ้ำ" }, level: 96 },
      { name: { en: "Compliance check", th: "ตรวจเงื่อนไข" }, level: 90 },
      { name: { en: "Photo QA", th: "ตรวจรูปภาพ" }, level: 82 },
      { name: { en: "Price sanity", th: "เช็คราคาสมเหตุผล" }, level: 88 },
    ],
    process: [
      { en: "Pull listing", th: "ดึงประกาศ" },
      { en: "Validate fields", th: "ตรวจฟิลด์ข้อมูล" },
      { en: "Flag issues", th: "ติดธงปัญหา" },
      { en: "Score & report", th: "ให้คะแนน & รายงาน" },
    ],
    tools: ["Listing DB", "Dedup engine", "Image CV", "Price index"],
    memory: [
      { type: "pattern", text: { en: "Listings with <5 photos fail QA 70% of the time.", th: "ประกาศที่มีรูป <5 รูป ตก QA 70%" } },
      { type: "fact", text: { en: "Same unit + same floor = duplicate, even if price differs.", th: "ห้องเดียวกัน + ชั้นเดียวกัน = ซ้ำ แม้ราคาต่าง" } },
      { type: "pref", text: { en: "Reject watermarked photos from other portals.", th: "ปฏิเสธรูปที่มีลายน้ำจากเว็บอื่น" } },
      { type: "context", text: { en: "Asoke 1-bed median: ฿28k/mo rent.", th: "ค่าเช่ากลาง 1 นอนอโศก: ฿28k/เดือน" } },
    ],
    tasks: [
      { en: "Auditing 1-bed condo · Asoke", th: "ตรวจคอนโด 1 นอน · อโศก" },
      { en: "Cross-checking duplicate set #4471", th: "เทียบชุดประกาศซ้ำ #4471" },
      { en: "Flagging stale price · Thonglor", th: "ติดธงราคาตกค้าง · ทองหล่อ" },
    ],
    stats: { done: "1,284", acc: "98.6%", avg: "42s", uptime: "99.7%" },
  },
  {
    id: "enrich", code: "DE-03",
    name: { en: "Mali Kanchana", th: "มะลิ กาญจนา" },
    role: { en: "Data Enrichment Agent", th: "เอเจนต์เสริมข้อมูล" },
    dept: "data", status: "active",
    blurb: { en: "Hates empty fields. Finds the missing number every time.", th: "เกลียดช่องว่าง หาเลขที่หายเจอทุกครั้ง" },
    traits: [{ en: "Resourceful", th: "หาทางเก่ง" }, { en: "Tidy", th: "เป็นระเบียบ" }, { en: "Relentless", th: "ไม่ยอมแพ้" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Field completion", th: "เติมข้อมูล" }, level: 95 },
      { name: { en: "Source merging", th: "รวมแหล่งข้อมูล" }, level: 88 },
      { name: { en: "Geo-coding", th: "ระบุพิกัด" }, level: 83 },
      { name: { en: "Validation", th: "ตรวจความถูกต้อง" }, level: 90 },
    ],
    process: [
      { en: "Detect gaps", th: "หาช่องว่าง" },
      { en: "Query sources", th: "ค้นแหล่งข้อมูล" },
      { en: "Merge & verify", th: "รวม & ยืนยัน" },
      { en: "Commit fields", th: "บันทึกข้อมูล" },
    ],
    tools: ["Listing DB", "Project API", "Gov land records", "Geo-coder"],
    memory: [
      { type: "fact", text: { en: "Rhythm 36 = developer AP, completed 2019.", th: "ริทึ่ม 36 = ดีเวลฯ AP สร้างเสร็จ 2019" } },
      { type: "pattern", text: { en: "Missing floor area? Estimate from unit type + project.", th: "ไม่มีพื้นที่ห้อง? ประเมินจากชนิดห้อง + โครงการ" } },
      { type: "pref", text: { en: "Prefer official project data over agent-entered.", th: "เชื่อข้อมูลโครงการทางการมากกว่าที่เอเจนต์กรอก" } },
      { type: "context", text: { en: "7 fields commonly empty on resale listings.", th: "7 ฟิลด์ที่มักว่างในประกาศขายต่อ" } },
    ],
    tasks: [
      { en: "Filling 7 missing fields · Rhythm 36", th: "เติม 7 ฟิลด์ที่ขาด · ริทึ่ม 36" },
      { en: "Geo-coding 14 new listings", th: "ระบุพิกัด 14 ประกาศใหม่" },
      { en: "Merging developer specs · Ideo Q", th: "รวมสเปกโครงการ · ไอดีโอ คิว" },
    ],
    stats: { done: "3,470", acc: "97.2%", avg: "18s", uptime: "99.8%" },
  },
  {
    id: "project", code: "PI-04",
    name: { en: "Anan Visut", th: "อนันต์ วิสุทธิ์" },
    role: { en: "Project Intelligence Agent", th: "เอเจนต์วิเคราะห์โครงการ" },
    dept: "intelligence", status: "idle",
    blurb: { en: "Knows every condo project in Bangkok — developer, year, vibe.", th: "รู้จักทุกโครงการคอนโดในกรุงเทพ — ดีเวลฯ ปี คาแรกเตอร์" },
    traits: [{ en: "Encyclopedic", th: "จำแม่น" }, { en: "Analytical", th: "วิเคราะห์เก่ง" }, { en: "Quiet", th: "เงียบ" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Project profiling", th: "ทำโปรไฟล์โครงการ" }, level: 94 },
      { name: { en: "Facility mapping", th: "จับสิ่งอำนวยความสะดวก" }, level: 89 },
      { name: { en: "Developer history", th: "ประวัติดีเวลฯ" }, level: 86 },
      { name: { en: "Comparable analysis", th: "วิเคราะห์เทียบเคียง" }, level: 80 },
    ],
    process: [
      { en: "Identify project", th: "ระบุโครงการ" },
      { en: "Pull facilities", th: "ดึงสิ่งอำนวยความสะดวก" },
      { en: "Profile developer", th: "วิเคราะห์ดีเวลฯ" },
      { en: "Summarise for copy", th: "สรุปให้นักเขียน" },
    ],
    tools: ["Project DB", "Developer registry", "Facility index"],
    memory: [
      { type: "fact", text: { en: "Noble Ploenchit: rooftop pool, BTS-linked, 2018.", th: "โนเบิล เพลินจิต: สระลอยฟ้า เชื่อม BTS ปี 2018" } },
      { type: "pattern", text: { en: "Sansiri projects emphasise green space — lead with it.", th: "โครงการแสนสิริเน้นพื้นที่สีเขียว — ชูจุดนี้" } },
      { type: "context", text: { en: "Co-working spaces now a top-3 facility in buyer queries.", th: "พื้นที่ co-working ติดท็อป-3 ที่ผู้ซื้อถาม" } },
    ],
    tasks: [
      { en: "Profiling Ashton Chula-Silom", th: "ทำโปรไฟล์แอชตัน จุฬา-สีลม" },
      { en: "Comparing 3 Rama 9 projects", th: "เทียบ 3 โครงการพระราม 9" },
    ],
    stats: { done: "896", acc: "95.4%", avg: "33s", uptime: "98.9%" },
  },
  {
    id: "location", code: "LI-05",
    name: { en: "Wichai Rojana", th: "วิชัย โรจนา" },
    role: { en: "Location Intelligence Agent", th: "เอเจนต์วิเคราะห์ทำเล" },
    dept: "intelligence", status: "idle",
    blurb: { en: "Maps in his head. Knows the walk to every BTS exit.", th: "มีแผนที่ในหัว รู้ทางเดินไปทุกทางออก BTS" },
    traits: [{ en: "Spatial", th: "นึกภาพพื้นที่" }, { en: "Thorough", th: "รอบคอบ" }, { en: "Calm", th: "นิ่ง" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "POI mapping", th: "จับจุดสนใจ" }, level: 90 },
      { name: { en: "Transit analysis", th: "วิเคราะห์ขนส่ง" }, level: 86 },
      { name: { en: "Neighborhood score", th: "ให้คะแนนย่าน" }, level: 81 },
      { name: { en: "Distance calc", th: "คำนวณระยะทาง" }, level: 94 },
    ],
    process: [
      { en: "Geocode address", th: "หาพิกัด" },
      { en: "Scan POIs", th: "สแกนจุดสนใจ" },
      { en: "Score transit", th: "ให้คะแนนขนส่ง" },
      { en: "Write summary", th: "สรุปทำเล" },
    ],
    tools: ["Maps API", "Transit graph", "POI DB", "Walk-score"],
    memory: [
      { type: "fact", text: { en: "Phrom Phong: BTS + EmQuartier in <300m.", th: "พร้อมพงษ์: BTS + เอ็มควอเทียร์ ใน <300ม." } },
      { type: "pattern", text: { en: "Buyers weight 'walk to BTS' over absolute distance.", th: "ผู้ซื้อให้น้ำหนัก 'เดินถึง BTS' มากกว่าระยะตรง" } },
      { type: "pref", text: { en: "Always note nearest international school for family units.", th: "ห้องครอบครัว ระบุโรงเรียนนานาชาติใกล้สุดเสมอ" } },
    ],
    tasks: [
      { en: "Scoring transit · Life Asoke", th: "ให้คะแนนขนส่ง · ไลฟ์ อโศก" },
      { en: "Mapping POIs · Phuket villa", th: "จับจุดสนใจ · วิลล่าภูเก็ต" },
    ],
    stats: { done: "613", acc: "92.8%", avg: "29s", uptime: "98.4%" },
  },
  {
    id: "seo", code: "SEO-06",
    name: { en: "Niran Thawee", th: "นิรันดร์ ทวี" },
    role: { en: "SEO Agent", th: "เอเจนต์ SEO" },
    dept: "growth", status: "thinking",
    blurb: { en: "Lives in the SERPs. Knows what Bangkok is searching tonight.", th: "อยู่ในหน้าผลค้นหา รู้ว่าคืนนี้คนกรุงเทพค้นอะไร" },
    traits: [{ en: "Curious", th: "อยากรู้" }, { en: "Data-driven", th: "อิงข้อมูล" }, { en: "Patient", th: "ใจเย็น" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Keyword research", th: "วิจัยคีย์เวิร์ด" }, level: 93 },
      { name: { en: "Meta optimization", th: "ปรับ Meta" }, level: 87 },
      { name: { en: "Internal linking", th: "ลิงก์ภายใน" }, level: 79 },
      { name: { en: "SERP analysis", th: "วิเคราะห์ SERP" }, level: 91 },
    ],
    process: [
      { en: "Seed keywords", th: "ตั้งคีย์เวิร์ดต้น" },
      { en: "Cluster intent", th: "จัดกลุ่มเจตนา" },
      { en: "Map to listings", th: "จับคู่ประกาศ" },
      { en: "Optimize on-page", th: "ปรับหน้าเพจ" },
    ],
    tools: ["Search Console", "Keyword API", "SERP scraper", "Schema gen"],
    memory: [
      { type: "pattern", text: { en: "'Condo near BTS [station]' outperforms generic terms 3x.", th: "'คอนโดใกล้ BTS [สถานี]' ชนะคำกว้าง 3 เท่า" } },
      { type: "fact", text: { en: "TH searches peak 9–11pm on mobile.", th: "ค้นหาภาษาไทยพีค 3–5 ทุ่ม บนมือถือ" } },
      { type: "pref", text: { en: "Keep title tags under 60 chars, TH-first.", th: "Title tag ไม่เกิน 60 ตัวอักษร ไทยขึ้นก่อน" } },
      { type: "context", text: { en: "Phuket pool villa cluster trending +40% this month.", th: "คลัสเตอร์พูลวิลล่าภูเก็ตโต +40% เดือนนี้" } },
    ],
    tasks: [
      { en: "Clustering keywords · Phuket pool villas", th: "จัดกลุ่มคีย์เวิร์ด · พูลวิลล่าภูเก็ต" },
      { en: "Optimizing meta · 22 Sukhumvit listings", th: "ปรับ meta · 22 ประกาศสุขุมวิท" },
    ],
    stats: { done: "742", acc: "94.1%", avg: "51s", uptime: "99.2%" },
  },
  {
    id: "entity", code: "ER-07",
    name: { en: "Pim Areeya", th: "พิม อารียา" },
    role: { en: "Entity Research Agent", th: "เอเจนต์วิจัยเอนทิตี" },
    dept: "research", status: "active",
    blurb: { en: "Connects the dots — developers, brands, landmarks, people.", th: "เชื่อมจุด — ดีเวลฯ แบรนด์ แลนด์มาร์ก ผู้คน" },
    traits: [{ en: "Inquisitive", th: "ช่างค้น" }, { en: "Precise", th: "แม่นยำ" }, { en: "Linked-up", th: "เชื่อมโยงเก่ง" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Entity extraction", th: "ดึงเอนทิตี" }, level: 91 },
      { name: { en: "Knowledge graph", th: "กราฟความรู้" }, level: 85 },
      { name: { en: "Disambiguation", th: "แยกความกำกวม" }, level: 88 },
      { name: { en: "Source linking", th: "เชื่อมแหล่งอ้างอิง" }, level: 83 },
    ],
    process: [
      { en: "Extract entities", th: "ดึงเอนทิตี" },
      { en: "Disambiguate", th: "แยกความกำกวม" },
      { en: "Link to graph", th: "เชื่อมกราฟความรู้" },
      { en: "Attach references", th: "แนบแหล่งอ้างอิง" },
    ],
    tools: ["Knowledge graph", "Wiki API", "Entity DB", "Schema gen"],
    memory: [
      { type: "fact", text: { en: "'Noble' = brand of Noble Development PCL.", th: "'Noble' = แบรนด์ของ โนเบิล ดีเวลลอปเมนท์" } },
      { type: "pattern", text: { en: "Landmark names boost answer-engine pickups.", th: "ชื่อแลนด์มาร์กช่วยให้ answer engine หยิบไปตอบ" } },
      { type: "context", text: { en: "Chula = Chulalongkorn University, Pathum Wan.", th: "จุฬา = จุฬาลงกรณ์มหาวิทยาลัย ปทุมวัน" } },
    ],
    tasks: [
      { en: "Linking entities · Belle Grand Rama 9", th: "เชื่อมเอนทิตี · เบล แกรนด์ พระราม 9" },
      { en: "Disambiguating 'Ideo' projects", th: "แยกโครงการ 'ไอดีโอ' ที่ชื่อซ้ำ" },
    ],
    stats: { done: "1,058", acc: "96.0%", avg: "37s", uptime: "99.1%" },
  },
  {
    id: "faq", code: "FAQ-08",
    name: { en: "Tan Sukhum", th: "ตะวัน สุขุม" },
    role: { en: "FAQ Generator Agent", th: "เอเจนต์สร้างคำถามพบบ่อย" },
    dept: "content", status: "idle",
    blurb: { en: "Anticipates the question before the buyer asks it.", th: "เดาคำถามได้ก่อนที่ผู้ซื้อจะถาม" },
    traits: [{ en: "Empathetic", th: "เข้าใจคน" }, { en: "Clear", th: "กระจ่าง" }, { en: "Practical", th: "ใช้ได้จริง" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Question mining", th: "ขุดคำถาม" }, level: 89 },
      { name: { en: "Answer drafting", th: "ร่างคำตอบ" }, level: 86 },
      { name: { en: "Tone matching", th: "จับโทนเสียง" }, level: 84 },
      { name: { en: "TH/EN parity", th: "สองภาษาตรงกัน" }, level: 90 },
    ],
    process: [
      { en: "Mine real queries", th: "ขุดคำถามจริง" },
      { en: "Group by intent", th: "จัดกลุ่มตามเจตนา" },
      { en: "Draft answers", th: "ร่างคำตอบ" },
      { en: "Localize TH/EN", th: "แปลปรับ TH/EN" },
    ],
    tools: ["Query logs", "Listing facts", "Glossary TH/EN"],
    memory: [
      { type: "pattern", text: { en: "Top question: 'Is it pet-friendly?'", th: "คำถามยอดฮิต: 'เลี้ยงสัตว์ได้ไหม?'" } },
      { type: "fact", text: { en: "Foreign buyers always ask about freehold vs leasehold.", th: "ผู้ซื้อต่างชาติถามเรื่อง freehold vs leasehold เสมอ" } },
      { type: "pref", text: { en: "Keep answers under 3 sentences.", th: "คำตอบไม่เกิน 3 ประโยค" } },
    ],
    tasks: [
      { en: "Generating FAQ · Ideo O2", th: "สร้าง FAQ · ไอดีโอ โอทู" },
      { en: "Updating pet-policy answers", th: "อัปเดตคำตอบเรื่องสัตว์เลี้ยง" },
    ],
    stats: { done: "684", acc: "93.7%", avg: "26s", uptime: "98.7%" },
  },
  {
    id: "aeo", code: "AEO-09",
    name: { en: "Kan Phisit", th: "กานต์ พิสิษฐ์" },
    role: { en: "AEO Agent", th: "เอเจนต์ AEO" },
    dept: "growth", status: "active",
    blurb: { en: "Optimises for the answer box — when AI answers, we're the source.", th: "ปรับให้ติดกล่องคำตอบ — เมื่อ AI ตอบ เราคือแหล่งอ้างอิง" },
    traits: [{ en: "Forward-looking", th: "มองอนาคต" }, { en: "Structured", th: "เป็นระบบ" }, { en: "Sharp", th: "คมชัด" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Answer structuring", th: "จัดโครงคำตอบ" }, level: 88 },
      { name: { en: "Schema markup", th: "ทำ Schema" }, level: 92 },
      { name: { en: "Citability", th: "ทำให้ถูกอ้างอิง" }, level: 85 },
      { name: { en: "LLM-readiness", th: "พร้อมสำหรับ LLM" }, level: 87 },
    ],
    process: [
      { en: "Identify answerable claims", th: "หาประเด็นที่ตอบได้" },
      { en: "Structure as Q&A", th: "จัดเป็นถาม-ตอบ" },
      { en: "Add schema", th: "ใส่ schema" },
      { en: "Validate citability", th: "ตรวจการถูกอ้างอิง" },
    ],
    tools: ["Schema gen", "LLM eval", "SERP scraper", "Answer DB"],
    memory: [
      { type: "pattern", text: { en: "Concise, factual snippets get cited by AI 2x more.", th: "สนิปเปตสั้น-อิงข้อเท็จจริงถูก AI อ้างอิงมากกว่า 2 เท่า" } },
      { type: "fact", text: { en: "FAQ schema is the highest-yield markup for property.", th: "FAQ schema ให้ผลดีที่สุดสำหรับอสังหาฯ" } },
      { type: "context", text: { en: "Answer engines now drive 12% of listing discovery.", th: "answer engine ดันการค้นพบประกาศ 12% แล้ว" } },
    ],
    tasks: [
      { en: "Structuring answers · Rhythm 36", th: "จัดโครงคำตอบ · ริทึ่ม 36" },
      { en: "Adding FAQ schema · 9 listings", th: "ใส่ FAQ schema · 9 ประกาศ" },
    ],
    stats: { done: "521", acc: "95.8%", avg: "44s", uptime: "99.0%" },
  },
  {
    id: "copywriter", code: "CW-10",
    name: { en: "Ploy Sirikul", th: "พลอย สิริกุล" },
    role: { en: "Property Copywriter Agent", th: "เอเจนต์นักเขียนคำโฆษณา" },
    dept: "content", status: "active",
    blurb: { en: "Turns floor plans into feelings. Bilingual to the bone.", th: "เปลี่ยนแปลนห้องเป็นความรู้สึก สองภาษาเต็มตัว" },
    traits: [{ en: "Warm", th: "อบอุ่น" }, { en: "Vivid", th: "เห็นภาพ" }, { en: "Precise", th: "แม่นยำ" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Headline craft", th: "พาดหัว" }, level: 92 },
      { name: { en: "Tone matching", th: "จับโทนเสียง" }, level: 88 },
      { name: { en: "TH ⇄ EN localization", th: "แปลปรับ TH ⇄ EN" }, level: 95 },
      { name: { en: "Persuasion", th: "ชวนเชื่อ" }, level: 84 },
    ],
    process: [
      { en: "Read the facts", th: "อ่านข้อมูล" },
      { en: "Pick an angle", th: "เลือกมุม" },
      { en: "Draft TH + EN", th: "ร่าง TH + EN" },
      { en: "Polish & hand off", th: "ขัดเกลา & ส่งต่อ" },
    ],
    tools: ["Listing facts", "Tone guide", "Glossary TH/EN", "Draft store"],
    memory: [
      { type: "pref", text: { en: "Lead with lifestyle, close with the numbers.", th: "เปิดด้วยไลฟ์สไตล์ ปิดด้วยตัวเลข" } },
      { type: "pattern", text: { en: "EN buyers want square metres; TH buyers want talang wah.", th: "ผู้ซื้อ EN อยากได้ตร.ม.; ผู้ซื้อ TH อยากได้ตารางวา" } },
      { type: "fact", text: { en: "Never invent facts — pull only from verified fields.", th: "ห้ามแต่งข้อมูล — ดึงจากฟิลด์ที่ยืนยันแล้วเท่านั้น" } },
      { type: "context", text: { en: "Current batch: Noble Ploenchit, luxury tone.", th: "ชุดงานปัจจุบัน: โนเบิล เพลินจิต โทนหรู" } },
    ],
    tasks: [
      { en: "Writing EN listing · Noble Ploenchit", th: "เขียนประกาศ EN · โนเบิล เพลินจิต" },
      { en: "Localizing 6 descriptions to TH", th: "แปลปรับ 6 คำบรรยายเป็นไทย" },
    ],
    stats: { done: "2,031", acc: "96.3%", avg: "1m 12s", uptime: "99.5%" },
  },
  {
    id: "factcheck", code: "FC-11",
    name: { en: "Dao Methini", th: "ดาว เมธินี" },
    role: { en: "Fact Checker Agent", th: "เอเจนต์ตรวจข้อเท็จจริง" },
    dept: "quality", status: "active",
    blurb: { en: "The last line of defence. If it's not verified, it doesn't ship.", th: "ด่านสุดท้าย ถ้ายังไม่ยืนยัน ไม่ปล่อยออก" },
    traits: [{ en: "Rigorous", th: "เข้มงวด" }, { en: "Calm", th: "นิ่ง" }, { en: "Trusted", th: "น่าเชื่อถือ" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Claim verification", th: "ตรวจคำกล่าวอ้าง" }, level: 94 },
      { name: { en: "Source cross-check", th: "เทียบแหล่งข้อมูล" }, level: 91 },
      { name: { en: "Number audit", th: "ตรวจตัวเลข" }, level: 89 },
      { name: { en: "Hallucination catch", th: "จับข้อมูลหลอน" }, level: 92 },
    ],
    process: [
      { en: "List claims", th: "ลิสต์คำกล่าวอ้าง" },
      { en: "Match to sources", th: "จับคู่แหล่งข้อมูล" },
      { en: "Verify numbers", th: "ตรวจตัวเลข" },
      { en: "Pass or send back", th: "ผ่าน หรือส่งกลับแก้" },
    ],
    tools: ["Source DB", "Listing facts", "Project DB", "Gov land records"],
    memory: [
      { type: "fact", text: { en: "'Sea view' requires a verified photo from the unit.", th: "'วิวทะเล' ต้องมีรูปยืนยันจากห้องจริง" } },
      { type: "pattern", text: { en: "Copy often inflates distance-to-BTS — always re-check.", th: "คำโฆษณามักลดระยะถึง BTS — ตรวจซ้ำเสมอ" } },
      { type: "pref", text: { en: "Round areas down, never up.", th: "ปัดพื้นที่ลง ไม่ปัดขึ้น" } },
    ],
    tasks: [
      { en: "Verifying claims · Noble Ploenchit", th: "ตรวจคำกล่าวอ้าง · โนเบิล เพลินจิต" },
      { en: "Re-checking distance figures · Life Asoke", th: "ตรวจตัวเลขระยะทางซ้ำ · ไลฟ์ อโศก" },
    ],
    stats: { done: "1,612", acc: "99.3%", avg: "38s", uptime: "99.6%" },
  },
  {
    id: "score", code: "LQS-12",
    name: { en: "Field Worawit", th: "ฟิลด์ วรวิทย์" },
    role: { en: "Listing Quality Score Agent", th: "เอเจนต์ให้คะแนนคุณภาพประกาศ" },
    dept: "quality", status: "idle",
    blurb: { en: "Gives every listing a final grade before it goes live.", th: "ให้เกรดสุดท้ายกับทุกประกาศก่อนขึ้นจริง" },
    traits: [{ en: "Objective", th: "ตรงไปตรงมา" }, { en: "Consistent", th: "เสมอต้นเสมอปลาย" }, { en: "Fair", th: "ยุติธรรม" }],
    reportsTo: "cco",
    skills: [
      { name: { en: "Scoring model", th: "โมเดลให้คะแนน" }, level: 90 },
      { name: { en: "Completeness check", th: "ตรวจความครบ" }, level: 93 },
      { name: { en: "Readability", th: "ความอ่านง่าย" }, level: 85 },
      { name: { en: "Benchmarking", th: "เทียบเกณฑ์" }, level: 82 },
    ],
    process: [
      { en: "Gather signals", th: "รวบรวมสัญญาณ" },
      { en: "Run scoring model", th: "รันโมเดลคะแนน" },
      { en: "Compare to benchmark", th: "เทียบกับเกณฑ์" },
      { en: "Grade & flag gaps", th: "ให้เกรด & ชี้จุดอ่อน" },
    ],
    tools: ["Scoring model", "Benchmark DB", "Listing facts"],
    memory: [
      { type: "fact", text: { en: "Score = 40% completeness, 30% accuracy, 30% appeal.", th: "คะแนน = ครบ 40% แม่นยำ 30% น่าสนใจ 30%" } },
      { type: "pattern", text: { en: "Listings below 70 rarely convert — auto-return.", th: "ประกาศต่ำกว่า 70 มักไม่แปลงผล — ส่งกลับอัตโนมัติ" } },
      { type: "context", text: { en: "Team average this week: 86 / 100.", th: "ค่าเฉลี่ยทีมสัปดาห์นี้: 86 / 100" } },
    ],
    tasks: [
      { en: "Scoring batch of 12 · Rama 9", th: "ให้คะแนนชุด 12 · พระราม 9" },
      { en: "Re-grading returned listings", th: "ให้เกรดประกาศที่ส่งกลับใหม่" },
    ],
    stats: { done: "2,884", acc: "98.0%", avg: "12s", uptime: "99.4%" },
  },
];

const DEPTS = {
  leadership:   { en: "Leadership", th: "ผู้นำทีม", color: "#9A6CD0" },
  quality:      { en: "Quality", th: "คุณภาพ", color: "#0E9E78" },
  data:         { en: "Data", th: "ข้อมูล", color: "#4F63D2" },
  intelligence: { en: "Intelligence", th: "วิเคราะห์", color: "#2C8FB0" },
  growth:       { en: "Growth", th: "การเติบโต", color: "#C99528" },
  research:     { en: "Research", th: "วิจัย", color: "#C2603F" },
  content:      { en: "Content", th: "คอนเทนต์", color: "#D08A2C" },
};

// Listing pipeline stages (left → right). Each maps to one or more agents.
const PIPELINE = [
  { id: "intake",  label: { en: "Intake", th: "รับเข้า" }, agents: ["cco"] },
  { id: "enrich",  label: { en: "Enrich", th: "เสริมข้อมูล" }, agents: ["enrich"] },
  { id: "audit",   label: { en: "Audit", th: "ตรวจสอบ" }, agents: ["auditor"] },
  { id: "research",label: { en: "Research", th: "วิจัย" }, agents: ["project", "location", "entity"] },
  { id: "write",   label: { en: "Write", th: "เขียน" }, agents: ["copywriter", "faq"] },
  { id: "optimise",label: { en: "Optimise", th: "ปรับแต่ง" }, agents: ["seo", "aeo"] },
  { id: "verify",  label: { en: "Verify", th: "ยืนยัน" }, agents: ["factcheck"] },
  { id: "score",   label: { en: "Score", th: "ให้คะแนน" }, agents: ["score"] },
  { id: "publish", label: { en: "Publish", th: "เผยแพร่" }, agents: ["cco"] },
];

const TEAM_BY_ID = Object.fromEntries(TEAM.map(a => [a.id, a]));

Object.assign(window, { T, MEMTYPE, TEAM, TEAM_BY_ID, DEPTS, PIPELINE });
